apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: di10x6mxk-dotnet-basic
  janus-idp.io/tekton: di10x6mxk-dotnet-basic
  backstage.io/kubernetes-id: di10x6mxk-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: di10x6mxk-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
